### PR TITLE
Two schemas

### PR DESCRIPTION
**Pull request by BryanPSK**
set default active profile to dev

### CODE REVIEW

**Review by fabkoh — COMMENTED** [review]
Is there a need to have the jasypt.encryptor.password property in -dev.properties?

**Comment by ong-wei-hong** [comment]
> Is there a need to have the jasypt.encryptor.password property in -dev.properties?

removed it and it works

**Comment by fabkoh** [comment]
> > Is there a need to have the jasypt.encryptor.password property in -dev.properties?
> 
> removed it and it works

Ok thanks, will approve and merge

**Review by fabkoh — APPROVED** [review]
Approved

**Pull request merged**
